
// Generated By Leetcode2IDE
#include <bits/stdc++.h>
using namespace std;

class Solution
{
public:
    int longestString(int x, int y, int z)
    {
        int ans = 0;
        if (x == y)
        {
            ans += 2 * (x + y) + 2 * z;
            return ans;
        }
        int mini = min(x, y);
        ans += 2 * (mini + mini);
        // cout << ans << endl;
        int a = abs(x - y);
        ans += 2 * z + 2;
        // cout << ans << endl;
        return ans;
    }
};

int main()
{

    Solution leetcode2IDE;
    int x1 = 9;
    int y1 = 9;
    int z1 = 34;
    int output_1 = 12;
    if (leetcode2IDE.longestString(x1, y1, z1) == output_1)
    {
        cout << "Sample #1 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #1 : Wrong Answer" << endl;
    }

    int x2 = 3;
    int y2 = 2;
    int z2 = 2;
    int output_2 = 14;
    if (leetcode2IDE.longestString(x2, y2, z2) == output_2)
    {
        cout << "Sample #2 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #2 : Wrong Answer" << endl;
    }

    return 0;
}
