
// Generated By Leetcode2IDE
#include <bits/stdc++.h>
using namespace std;

class Solution
{
private:
    int f(int idx, string &str, vector<string> &dictionary)
    {
        if (idx >= str.size())
            return 0;
        // for(int i = )
    }

public:
    int minExtraChar(string s, vector<string> &dictionary)
    {
        int ans = f(0, s, dictionary);
    }
};

int main()
{

    Solution leetcode2IDE;
    string s1 = "leetscode";
    vector<string> dictionary1 = {"leet", "code", "leetcode"};
    int output_1 = 1;
    if (leetcode2IDE.minExtraChar(s1, dictionary1) == output_1)
    {
        cout << "Sample #1 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #1 : Wrong Answer" << endl;
    }

    string s2 = "sayhelloworld";
    vector<string> dictionary2 = {"hello", "world"};
    int output_2 = 3;
    if (leetcode2IDE.minExtraChar(s2, dictionary2) == output_2)
    {
        cout << "Sample #2 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #2 : Wrong Answer" << endl;
    }

    string s3 = "dwmodizxvvbosxxw";

    vector<string> dictionary3 = {"ox", "lb", "diz", "gu", "v", "ksv", "o", "nuq", "r", "txhe", "e", "wmo", "cehy", "tskz", "ds", "kzbu"};
    int output_3 = 7;
    if (leetcode2IDE.minExtraChar(s3, dictionary3) == output_3)
    {
        cout << "Sample #3 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #3 : Wrong Answer" << endl;
    }

    return 0;
}
