
// Generated By Leetcode2IDE
#include <bits/stdc++.h>
using namespace std;

class Solution
{
public:
    int minimizedStringLength(string s)
    {
        set<char> ss;
        for (auto x : s)
        {
            ss.insert(x);
        }
        return ss.size();
    }
};

int main()
{

    Solution leetcode2IDE;
    string s1 = "aaabc";
    int output_1 = 3;
    if (leetcode2IDE.minimizedStringLength(s1) == output_1)
    {
        cout << "Sample #1 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #1 : Wrong Answer" << endl;
    }

    string s2 = "cbbd";
    int output_2 = 3;
    if (leetcode2IDE.minimizedStringLength(s2) == output_2)
    {
        cout << "Sample #2 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #2 : Wrong Answer" << endl;
    }

    string s3 = "dddaaa";
    int output_3 = 2;
    if (leetcode2IDE.minimizedStringLength(s3) == output_3)
    {
        cout << "Sample #3 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #3 : Wrong Answer" << endl;
    }

    return 0;
}
