
// Generated By Leetcode2IDE
#include <bits/stdc++.h>
using namespace std;

class Solution
{
public:
    int makeTheIntegerZero(int num1, int num2)
    {
    }
};

int main()
{

    Solution leetcode2IDE;
    int num11 = 3;
    int num21 = -2;
    int output_1 = 3;
    if (leetcode2IDE.makeTheIntegerZero(num11, num21) == output_1)
    {
        cout << "Sample #1 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #1 : Wrong Answer" << endl;
    }

    int num12 = 5;
    int num22 = 7;
    int output_2 = -1;
    if (leetcode2IDE.makeTheIntegerZero(num12, num22) == output_2)
    {
        cout << "Sample #2 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #2 : Wrong Answer" << endl;
    }

    return 0;
}
