
// Generated By Leetcode2IDE
#include <bits/stdc++.h>
using namespace std;

class Solution
{
public:
    vector<int> survivedRobotsHealths(vector<int> &positions, vector<int> &healths, string directions)
    {
    }
};

int main()
{

    Solution leetcode2IDE;
    vector<int> positions1 = {5, 4, 3, 2, 1};
    vector<int> healths1 = {2, 17, 9, 15, 10};
    string directions1 = "RRRRR";
    vector<int> output_1 = {2, 17, 9, 15, 10};
    if (leetcode2IDE.survivedRobotsHealths(positions1, healths1, directions1) == output_1)
    {
        cout << "Sample #1 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #1 : Wrong Answer" << endl;
    }

    vector<int> positions2 = {3, 5, 2, 6};
    vector<int> healths2 = {10, 10, 15, 12};
    string directions2 = "RLRL";
    vector<int> output_2 = {14};
    if (leetcode2IDE.survivedRobotsHealths(positions2, healths2, directions2) == output_2)
    {
        cout << "Sample #2 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #2 : Wrong Answer" << endl;
    }

    vector<int> positions3 = {1, 2, 5, 6};
    vector<int> healths3 = {10, 10, 11, 11};
    string directions3 = "RLRL";
    vector<None> output_3 = {};
    if (leetcode2IDE.survivedRobotsHealths(positions3, healths3, directions3) == output_3)
    {
        cout << "Sample #3 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #3 : Wrong Answer" << endl;
    }

    return 0;
}
