
// Generated By Leetcode2IDE
#include <bits/stdc++.h>
using namespace std;

class Solution
{
public:
    int buyChoco(vector<int> &prices, int money)
    {
        sort(prices.begin(), prices.end());
        int sum = prices[0] + prices[1];
        if (money >= sum)
        {
            return money - sum;
        }
        else
        {
            return money;
        }
    }
};

int main()
{

    Solution leetcode2IDE;
    vector<int> prices1 = {1, 2, 2};
    int money1 = 3;
    int output_1 = 0;
    if (leetcode2IDE.buyChoco(prices1, money1) == output_1)
    {
        cout << "Sample #1 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #1 : Wrong Answer" << endl;
    }

    vector<int> prices2 = {3, 2, 3};
    int money2 = 3;
    int output_2 = 3;
    if (leetcode2IDE.buyChoco(prices2, money2) == output_2)
    {
        cout << "Sample #2 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #2 : Wrong Answer" << endl;
    }

    return 0;
}
