
// Generated By Leetcode2IDE
#include <bits/stdc++.h>
using namespace std;



class Solution {
public:
    int countPairs(vector<int>& nums, int target) {
        
    }
};


int main() {
	
	Solution leetcode2IDE;
	vector<int> nums1 = {-1,1,2,3,1};
	int target1 = 2;
	int output_1 = 3;
	if(leetcode2IDE.countPairs(nums1,target1)==output_1){
		cout << "Sample #1 : Accepted" << endl;
	}else{
		cout << "Sample #1 : Wrong Answer" << endl;
	}

	vector<int> nums2 = {-6,2,5,-2,-7,-1,3};
	int target2 = -2;
	int output_2 = 10;
	if(leetcode2IDE.countPairs(nums2,target2)==output_2){
		cout << "Sample #2 : Accepted" << endl;
	}else{
		cout << "Sample #2 : Wrong Answer" << endl;
	}

	


	return 0;
}
	