
// Generated By Leetcode2IDE
#include <bits/stdc++.h>
using namespace std;

class Solution
{
public:
    string finalString(string s)
    {
        string str = "";
        for (auto x : s)
        {
            if (x != 'i')
            {
                str += x;
            }
            else
            {
                reverse(str.begin(), str.end());
            }
        }
        return str;
    }
};

int main()
{

    Solution leetcode2IDE;
    string s1 = "string";
    string output_1 = "rtsng";
    if (leetcode2IDE.finalString(s1) == output_1)
    {
        cout << "Sample #1 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #1 : Wrong Answer" << endl;
    }

    string s2 = "poiinter";
    string output_2 = "ponter";
    if (leetcode2IDE.finalString(s2) == output_2)
    {
        cout << "Sample #2 : Accepted" << endl;
    }
    else
    {
        cout << "Sample #2 : Wrong Answer" << endl;
    }

    return 0;
}
